name: Alfresco Greenmail CI

on:
  pull_request:
    branches:
      - master
      - support/**
  push:
    branches:
      - master
      - support/**
  workflow_dispatch:

jobs:
  build_and_release:
      name: "Build and Release"
      uses: Alfresco/alfresco-build-tools/.github/workflows/build-and-release-maven.yml@v7.0.0
      secrets: inherit
      with:
        release-branches: "^master$|^support/.+$"
        build-args: "-Dmaven.javadoc.skip=true"
